name: Approve Security PRs

on: pull_request 

permissions: 
  pull-requests: write 

jobs:
  approve: 
    runs-on: ubuntu-latest 
    if: contains(github.event.pull_request.title, 'security')
    steps: 
      - run: | 
          curl --request POST \ 
          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \ 
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \ 
          --header 'content-type: application/json' \ 
          -d '{"event":"APPROVE"}' 