name: Approve Security PRs

on: pull_request 

permissions: 
  pull-requests: write 

jobs:
  approve: 
    runs-on: ubuntu-latest 
    if: contains(github.event.pull_request.title, 'security')
    steps: 
      - run: | 
          curl -X POST \ 
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \ 
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \ 
          -d '{"event":"APPROVE"}' 